= Dauphine Pole Info
:sectanchors:

image:https://travis-ci.org/saraTag/Dauphine-Pole-Info.svg?branch=master["Build Status", link="https://travis-ci.org/saraTag/Dauphine-Pole-Info"]

= Les membres du groupe:

* Sara TAGZIRIA
* Ouaaz Chahine
* Lahsen Jannani
* Anas BEN EL MAHJOUB

= Vue globale sur l’ensemble du projet:

* Nous allons nous baser sur le projet Dauphine-Pole-Info déjà existant, pour l’enrichir avec les fonctionnalités choisies par tous les membres du groupe.
* Nous avons répartie la réalisation du projet sur 3 sprints, chaque sprint correspond à la finalisation de quatre fonctionnalités.
* Le choix des fonctionnalités par sprint repose sur l’indépendance de ses derniers, nous allons commencé par celles qui sont les plus indépendantes pour avoir une flexibilité de livraison de chaque membre.
* Les démarches qui nous semblent dépendantes sont réservées aux derniers sprints.
* Nous pouvons éventuellement à tout moment avancer ou reporter une fonctionnalité qui nous semble difficile à livrer dans les temps ou qui depend d’un code qui serait absent ou incomplet.
* Nous mettrons à jour le readme au fur et à mesure des changements effectués.
* Le projet va être mis sur le depot en branche dev, nous seront toujours en attente de la validation de Monsieur Olivier CAILLOUX avant chaque merge dans la branche master.
* Chaque membre est engagé à faire les tests unitaires qui concerne l’ensemble du code modifié par lui afin d’avoir une traçabilité de debugage tout cela garantir une transparence et définir les responsabilités de chacun.
* Nous allons tout le long de la réalisation de ce projet essayer de fixer des réunions pour s’entraider et être au courant de l’état d’avancement.

*Sprint 1:*

* TAGZIRIA Sara : AutoDB: (1 Point)
 
Automatiser la création d’une BD MySQL de schéma attendu par l’application PoleInfo3.
 
* Ouaaz Chahine : Basics (1 Point)

Des objets pour stocker une personne et un cours, en vue de stocker les éléments de la base existante. Même chose pour Master et toutes informations nécessaires pour lier cours, enseignants et master (voir schéma SQL).

* Anas : Prefs (1 Point)

Un objet permet de stocker les préférences d’un étudiant concernant les cours facultatifs auxquels il a accès. Pouvoir l’encoder et décoder en JSON.

* Lahsen Jannani : basicServlets (1 Point)

Chaque objet de base Thing (Pour Thing valant Course, Person) a un id et trois servlets associées : setThing(id, txt), où txt est la représentation textuelle de Thing, getThing(id), et setThing(id, field1, field2, …). Les servlets ne permettent pas de modifier les interactions entre objets (par exemple de changer l’enseignant d’un cours), seulement les détails des objets eux-mêmes (par exemple le titre d’un cours). 

*Sprint 2:*

* TAGZIRIA Sara : BasicClient (1 Point)

Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la modification des informations de base de Course et Person. 

* Ouaaz Chahine : SetDB (1,5 Point )

Implémenter des entités JPA et les méthodes permettant d’écrire et de lire depuis la BD de façon à garantir la compatibilité avec l’application existante.

* Anas : ServletPref (1 Point )

Servlet setPref(id étudiant, pref), getPref(id étudiant), getPrefByCourse(id course) qui retourne (en JSON) les préférences indiquées par tous les étudiants ayant choisi ce cours.

* Lahsen Jannani : LinkServlets (0.5 Point) + Repr (0.5 Point)

Servlet permettant de récupérer, effacer, ajouter des liens entre master, cours et person, par id uniquement. 

*Sprint 3:*

* TAGZIRIA Sara : ObjectsXML (1 Point)

Encoder / décoder une partie de vos objets de base en XML. Repartir du schéma CDM-fr, simplifié. (« Vos objets de base » comprend ici Master.) Encoder / décoder le reste de vos objets de base en JSON, y compris les relations.

* Ouaaz Chahine : SOAP (1 Point)

Transformer certains servlets pour en faire des services SOAP. 

* Anas : Lib (1 Point)

Isoler la partie bibliothèque du reste du code. La publier comme un projet Maven indépendant (suffixer le nom du projet de -lib) et faire dépendre le reste du code de cette bibliothèque. Isoler la partie client du reste du code, publier comme un projet indépendant (ProjectName-client). Publier la partie serveur comme un projet indépendant (ProjectName). 

* Lahsen Jannani : ExtBasicServlets (1 Point)

Étendre servlets existants pour accepter et renvoyer à la demande du XML ou JSON en plus du texte. Transformer en REST. Cookie permet de mémoriser un id person, il est utilisé si l’id person n’est pas fourni, pour les servlets qui requièrent ce paramètre. 

Comme les deux fonctionnalités *lib* et *SOAP* ne sont pas prioritaires, nous allons réflechir à les remplacer par dautres fonctionnalités plus urgentes .
