
= Dauphine Pole Info 2017
:sectanchors:

image:https://travis-ci.org/saraTag/Dauphine-Pole-Info.svg?branch=master["Build Status", link="https://travis-ci.org/saraTag/Dauphine-Pole-Info"]

A Java project developed during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] M2 MIAGE). The code is jointly copyrighted by Olivier Cailloux and the following students:

* Fatima-Ezzahra Abbar
* Clement Boudville
* Mamery Doumbia
* Bleriot Kuate Kamga

The code is hereby published under the MIT License, with their permission.

== Original description
Installation de poleinfo3

Un serveur PHP et une base mySQL sont nécessaires : vous pouvez installer wamp,xamp ou mamp suivant votre OS.  
La démarche suivante a été réalisée avec wamp.  
  
1. Récupérer le code sur https://github.com/oliviercailloux/poleinfo3  
2. Déplacer le code dans le répertoire <www> de wamp  
3. Créer une base de données mySQL nommée "Master"  
  3.1 Soit en ligne de commande : mysqladmin -u root -p create Master  
  3.2 Soit avec phpMyAdmin  
4. Importer le fichier Schema.sql dans la base de données  
  4.1 ligne de commande : mysql -u root -p Master < Schema.sql
  4.2 ou avec phpMyAdmin
5. Indiquer les identifiants d'accès à la DB dans "DBinfo.php"
6. Activer les *short open tags* dans la configuration PHP
7. Accéder à l'application ! 
8. (Vous pouvez éventuellement réduire le niveau des erreurs rapportées pour ne pas prendre en compte les dépréciations)

= Dauphine Pole Info 2018
:sectanchors:

image:https://travis-ci.org/saraTag/Dauphine-Pole-Info.svg?branch=master["Build Status", link="https://travis-ci.org/saraTag/Dauphine-Pole-Info"]


= Les membres du groupe:

* Sara TAGZIRIA
* Ouaaz Chahine
* Lahsen Jannani
* Anas BEN EL MAHJOUB

= Template 

Ce projet utilise un template CRUD pour gérer l'objet master , (le lien de la template est ici : https://www.tutorialrepublic.com/snippets/preview.php?topic=bootstrap&file=crud-data-table-for-database-with-modal-form) - j'ai séparé le code html css et js parce qu'il était dans le meme fichier dans la template initiale-

= Vue globale sur l’ensemble du projet:

* Nous allons nous baser sur le projet Dauphine-Pole-Info déjà existant, pour l’enrichir avec les fonctionnalités choisies par tous les membres du groupe.
* Nous avons répartie la réalisation du projet sur 3 sprints, chaque sprint correspond à la finalisation de quatre fonctionnalités.
* Le choix des fonctionnalités par sprint repose sur l’indépendance de ses derniers, nous allons commencé par celles qui sont les plus indépendantes pour avoir une flexibilité de livraison de chaque membre.
* Les démarches qui nous semblent dépendantes sont réservées aux derniers sprints.
* Nous pouvons éventuellement à tout moment avancer ou reporter une fonctionnalité qui nous semble difficile à livrer dans les temps ou qui depend d’un code qui serait absent ou incomplet.
* Nous mettrons à jour le readme au fur et à mesure des changements effectués.
* Le projet va être mis sur le depot en branche dev, nous seront toujours en attente de la validation de Monsieur Olivier CAILLOUX avant chaque merge dans la branche master.
* Chaque membre est engagé à faire les tests unitaires qui concerne l’ensemble du code modifié par lui afin d’avoir une traçabilité de debugage tout cela garantir une transparence et définir les responsabilités de chacun.
* Nous allons tout le long de la réalisation de ce projet essayer de fixer des réunions pour s’entraider et être au courant de l’état d’avancement.

*Sprint 1:*

* TAGZIRIA Sara : *AutoDB* (1 Point)
 
Automatiser la création d’une BD MySQL de schéma attendu par l’application PoleInfo3.
 
* Ouaaz Chahine : *Basics* (1 Point)

Des objets pour stocker une personne et un cours, en vue de stocker les éléments de la base existante. Même chose pour Master et toutes informations nécessaires pour lier cours, enseignants et master (voir schéma SQL).

* Anas : *Prefs* (1 Point)

Un objet permet de stocker les préférences d’un étudiant concernant les cours facultatifs auxquels il a accès. Pouvoir l’encoder et décoder en JSON.

* Lahsen Jannani : *basicServlets* (1 Point)

Chaque objet de base Thing (Pour Thing valant Course, Person) a un id et trois servlets associées : setThing(id, txt), où txt est la représentation textuelle de Thing, getThing(id), et setThing(id, field1, field2, …). Les servlets ne permettent pas de modifier les interactions entre objets (par exemple de changer l’enseignant d’un cours), seulement les détails des objets eux-mêmes (par exemple le titre d’un cours). 

*Sprint 2:*

* TAGZIRIA Sara : *BasicClient* (1 Point)

Implémenter un client qui permet, avec un GUI rudimentaire ou en ligne de commande, la modification des informations de base de Course et Person. 

* Ouaaz Chahine : Affectation d'une nouvelle fonctionnalité plus tard.

* Anas : *ServletPref* (1 Point )

Servlet setPref(id étudiant, pref), getPref(id étudiant), getPrefByCourse(id course) qui retourne (en JSON) les préférences indiquées par tous les étudiants ayant choisi ce cours.

* Lahsen Jannani : *LinkServlets* (0.5 Point) + Repr (0.5 Point)

Servlet permettant de récupérer, effacer, ajouter des liens entre master, cours et person, par id uniquement. 

*Sprint 3:*

* TAGZIRIA Sara : *Template and Crud* (1 Point)

Ajouter un template : https://colorlib.com/wp/template/course/ et implémenter une interface graphique Crud pour Person .

* Ouaaz Chahine : *SOAP* (1 Point)

Transformer certains servlets pour en faire des services SOAP. 

* Anas : *Lib* (1 Point)

Isoler la partie bibliothèque du reste du code. La publier comme un projet Maven indépendant (suffixer le nom du projet de -lib) et faire dépendre le reste du code de cette bibliothèque. Isoler la partie client du reste du code, publier comme un projet indépendant (ProjectName-client). Publier la partie serveur comme un projet indépendant (ProjectName). 

* Lahsen Jannani : *Gui Master* (1 Point)

Intégrer une template pour crud master ainsi que la réalisation des script JS pour la consommation des services web add/update/delete de l'objet master

Comme les deux fonctionnalités *lib* et *SOAP* ne sont pas prioritaires, nous allons réflechir à les remplacer par dautres fonctionnalités plus urgentes .

= Remarques:
Pour ajouter une Personne, on utilise la servlet "addPerson", cette dernière fait appel à un constructeur qui prends une Person en paramètre  mais comme l'id d'une personne s'auto-génére et s'incrémente automatiquement au moment  de l'insertion dans la base de données, on ne s'en sert pas à l'interieur de ce constructeur.
